---
version: "3"
services:
  workspace:
    image: fjolsvin/vscode-golang-alpine
    container_name: go-template-workspace
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/workspace:cached
    command:
      - /bin/sh
      - -cex
      - |
        sudo chown "`id -u`:`id -g`" $$WORKDIR -R ;
        while sleep 1000; do :; done
