---
name: "docker-prd"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/docker-prd.yml"
      - "contrib/docker/prd/*"
  workflow_dispatch:
jobs:
  alpine:
    name: "build and push docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build and push docker image"
        shell: bash
        run: |
          set -ex ;
          docker buildx use "go-template" \
          || docker buildx create --use --name "go-template" --driver docker-container ;
          docker buildx bake --builder go-template prd ;
